-- 새롭게 생성한 USER
--SYSTEM 계정(권한자)에서 CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE; 로 생성하였음
-- SCOTT계정에서 권한을 부여하였음.
-- GRANT SELECT, INSERT ON TEMP TO ORCLSTUDY;
-- SCOTT의 TEMP 테이블에 대한 SELECT 권한을 부여받아서 SCOTT.TMEP를 SELECT 할 수 있음.
SELECT* FROM SCOTT.TEMP; 
INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCLSTUDY'); -- SCOTT.TEMP의 INSERT 권한을 부여받아서 실행이 가능하다.
--SCOTT 계정에서 권한을 취소하였음. REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;
SELECT* FROM SCOTT.TEMP; -- SELECT 불가능

-- 권한자 계정에서 ROLESTUDY 롤을  ORCLSTYDY 사용자에게 부여하였다.
-- ROLESTUDY 사용자 정의롤 : GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY ;
-- SYSTEM 계정에서 GRANT ROLESTUDY TO ORCLSTUDY 으로 사용자 정의 롤을 부여하였음.

-- 부여된 롤과 권한 확인하기 
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;



